# NumPy and Pandas Exercises 

## 1. Use various functions under Numerical Python to execute the following instructions.

In [3]:
# importing the numpy and pandas libraries
import numpy as np

### a. Generate a 2 by 3 matrix containing elements from 1 to 6 and multiply it by a scaler of two.  

In [4]:
# 2 by 3 matrix with elements from 1 to 6
matrix_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix_1)

[[1 2 3]
 [4 5 6]]


In [5]:
# multiplying matrix_1 by scaler 2
print(matrix_1 * 2)

[[ 2  4  6]
 [ 8 10 12]]


### b. Create a 3 by 3 identity matrix

In [6]:
# creating a 3 by 3 identity matrix
matrix_2 = np.array([[[1, 0, 0], [0, 1, 0], [0, 0, 1]]])
print(matrix_2)

[[[1 0 0]
  [0 1 0]
  [0 0 1]]]


### c. Create a 1-D array call arry1 which contains elements ranging from zero to twenty-seven. Convert arry1 to a 3-D arry2

In [7]:
# creating 1-D array from 1 to 27
#arry1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27])
arry1 = np.arange(1,28)
print(arry1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]


In [8]:
# converting 1-D to 3-D
arry2 = np.array([[[1,2,3,4,5,6,7,8,9], [10,11,12,13,14,15,16,17,18], [19,20,21,22,23,24,25,26,27]]])
print(arry2)

[[[ 1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18]
  [19 20 21 22 23 24 25 26 27]]]


### d. Create two 2-D arrays with the first array containing elements from 1 to 6 and the second array containing elements from 7 to 12. Horizontally stack the two arrays together.  Using the same set of arrays vertically stack the two arrays

In [9]:
# creating 2-D arrays
array1 = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
print(array1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [10]:
# horizontally stacked using hstack method
array2 = np.hstack(array1)
print(array2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [11]:
# vertically stacked using vstack method
array3 = np.vstack(array2)
print(array3)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


### e. Create an equally spaced sequence with a gap of 5 ranging from 0 to 100

In [12]:
# creating an equally spaced sequence using arange method
sequence = np.arange(0, 105, 5)
print(sequence)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


## 2. Use various Functions associated with Pandas to answer the following questions

In [13]:
# importing the pandas and numpy libraries
import pandas as pd

### a. Create a DataFrame named as students using a list of names of 5 students.

In [14]:
# creating a data frame with names of 5 students
students = pd.DataFrame(['David Tetteh', 'Godsway Amegbor', 'Precious Vifah', 'Raymond Agbenorhevi', 'Josephine Annan'])
print(studen

                     0
0         David Tetteh
1      Godsway Amegbor
2       Precious Vifah
3  Raymond Agbenorhevi
4      Josephine Annan


### b.Write a program to create a DataFrame teams using a list of names of Ghana Premier League Teams and the goals they scored in their previous five matches.

In [41]:
# declaring the array of goals scored
goals_scored = np.array([[2, 1, 5, 0, 2],[0, 4, 1, 2, 2],[6, 2, 0, 4, 1], [1, 3, 2, 0, 4], [3, 4, 1, 0, 1]])

#creating the data farme
teams = pd.DataFrame(goals_scored, index=['WAFA', 'Kumasi Asante Kotoko', 'Accra Great Olympics', 'Accra Hearts of Oak', 'Sekondi Hasakas'],
                columns=['Match1', 'Match2', 'Match3', 'Match4', 'Match5'])

teams

Match1  Match2  Match3  Match4  Match5
WAFA                       2       1       5       0       2
Kumasi Asante Kotoko       0       4       1       2       2
Accra Great Olympics       6       2       0       4       1
Accra Hearts of Oak        1       3       2       0       4
Sekondi Hasakas            3       4       1       0       1

### c. Write a program to create a DataFrame countries using a dictionary which stored country name, capitals, and populations of the country. Do this for West African Countries. 

In [16]:
# creating a dataframe for West African countries with their capitals and population

countries_name = ['Benin', 'Burkina Faso', 'Cape Verde', 'Gambia', 'Ghana', 'Guinea', 'Guinea Bissau', 'Ivory Coast', 'Liberia', 'Mali', 'Mauretania', 'Niger', 'Nigeria', 'Senegal', 'Sierra Leone', 'Togo']
caps = ['Porto Novo', 'Ouagadougou', 'Praia', 'Banjul', 'Accra', 'Conakry', 'Bissau', 'Yamoussoukro', 'Monrovia', 'Bamako', 'Nouakchott', 'Niamey', 'Abuja', 'Dakar', 'Freetown', 'Lome']
pop = [10.9, 18.7, 0.5, 2.0, 30.0, 12.4, 1.8, 23.7, 4.6, 18.0, 4.3, 20.7, 186.0, 15.0, 7.4, 7.6]


In [17]:
#assigning heading to the table using dictionary
dict_countries = {'Country Name':countries_name, 'Capital':caps, 'Population':pop}

In [18]:
# creating the dataframe of the west African countries with their details
country_details = pd.DataFrame(dict_countries)
country_details

Country Name       Capital  Population
0           Benin    Porto Novo        10.9
1    Burkina Faso   Ouagadougou        18.7
2      Cape Verde         Praia         0.5
3          Gambia        Banjul         2.0
4           Ghana         Accra        30.0
5          Guinea       Conakry        12.4
6   Guinea Bissau        Bissau         1.8
7     Ivory Coast  Yamoussoukro        23.7
8         Liberia      Monrovia         4.6
9            Mali        Bamako        18.0
10     Mauretania    Nouakchott         4.3
11          Niger        Niamey        20.7
12        Nigeria         Abuja       186.0
13        Senegal         Dakar        15.0
14   Sierra Leone      Freetown         7.4
15           Togo          Lome         7.6

### d. Consider the following data and write a programme to capture the data in python.

In [19]:
# creating the table
sno = [1,2,3,4,5,6,7]
team = ['Hearts of Oak', 'Asante Kotoko', 'Ebusua Dwarfs', 'Sekondi Hassacas', 'Okwahu United', 'Tano Bofoakwa', 'BA United']
gf = [120,90,90,80,78,70,71]
ga = [35,55,60,43,39,50,55]
pts = [80,60,60,55,53,49,44]

In [20]:
# Assigning heading to the table
teams_standing = {'SNO':sno, 'Team':team, 'GF':gf, 'GA':ga, 'PTS':pts}

In [21]:
#i. declaring the data frame
teams_table = pd.DataFrame(teams_standing)
teams_table

SNO              Team   GF  GA  PTS
0    1     Hearts of Oak  120  35   80
1    2     Asante Kotoko   90  55   60
2    3     Ebusua Dwarfs   90  60   60
3    4  Sekondi Hassacas   80  43   55
4    5     Okwahu United   78  39   53
5    6     Tano Bofoakwa   70  50   49
6    7         BA United   71  55   44

In [22]:
#ii.1. teams that conceeded more than 30 goals
teams_table[teams_table['GA']>30]

SNO              Team   GF  GA  PTS
0    1     Hearts of Oak  120  35   80
1    2     Asante Kotoko   90  55   60
2    3     Ebusua Dwarfs   90  60   60
3    4  Sekondi Hassacas   80  43   55
4    5     Okwahu United   78  39   53
5    6     Tano Bofoakwa   70  50   49
6    7         BA United   71  55   44

In [23]:
#.ii.2 teams that scored less than 80 goals
teams_table[teams_table['GF']<80]

SNO           Team  GF  GA  PTS
4    5  Okwahu United  78  39   53
5    6  Tano Bofoakwa  70  50   49
6    7      BA United  71  55   44

In [24]:
#.ii.3 teams that had less than 60 points
teams_table[teams_table['PTS']<60]

SNO              Team  GF  GA  PTS
3    4  Sekondi Hassacas  80  43   55
4    5     Okwahu United  78  39   53
5    6     Tano Bofoakwa  70  50   49
6    7         BA United  71  55   44

## 3. Use the Data Set Labelled cars to answer the following questions

In [25]:
#importing the pandas and numpy libraries
import numpy as np
import pandas as pd

In [26]:
# loading the cars2 csv file
cars = pd.read_csv("C:/Users/LENOVO/Downloads/cars 2.csv")
cars

index     company          car_type  wheel-base  length engine-type  \
0       0       Honda       Convertible        88.6   168.8        dohc   
1       1       Honda       Convertible        88.6   168.8        dohc   
2       2       Honda  Four Wheel Drive        94.5   171.2        ohcv   
3       3     Hyundai         Salon car        99.8   176.6         ohc   
4       4     Hyundai         Salon car        99.4   176.6         ohc   
..    ...         ...               ...         ...     ...         ...   
56     81      Toyota         Salon car        97.3   171.7         ohc   
57     82      Toyota         Salon car        97.3   171.7         ohc   
58     86      Toyota         Salon car        97.3   171.7         ohc   
59     87  Mitsubishi         Salon car       104.3   188.8         ohc   
60     88  Mitsubishi             Wagon       104.3   188.8         ohc   

   num-of-cylinders  egine_capacity  average-km     price  Unnamed: 10  \
0              four             7.4    33.79614   87717.5          NaN   
1              four             7.4    33.79614  107250.0          NaN   
2               six            10.3    30.57746  107250.0          NaN   
3              four             6.8    38.62416   90675.0          NaN   
4              five             7.7    28.96812  113425.0          NaN   
..              ...             ...         ...       ...          ...   
56             four             5.7    43.45218   51837.5          NaN   
57             four             3.5    59.54558   51967.5          NaN   
58             four             6.7    41.84284   64967.5          NaN   
59             four             7.6    37.01482   84110.0          NaN   
60             four             7.6    37.01482   87197.5          NaN   

    Unnamed: 11  Unnamed: 12  Unnamed: 13  Unnamed: 14  
0           NaN          NaN          NaN          NaN  
1           NaN          NaN          NaN          NaN  
2           NaN          NaN          NaN          NaN  
3           NaN          NaN          NaN          NaN  
4           NaN          NaN          NaN          NaN  
..          ...          ...          ...          ...  
56          NaN          NaN          NaN          NaN  
57          NaN          NaN          NaN          NaN  
58          NaN          NaN          NaN          NaN  
59          NaN          NaN          NaN          NaN  
60          NaN          NaN          NaN          NaN  

[61 rows x 15 columns]

### a. From the given dataset print the first and last five rows

In [27]:
# printing the first 5 rows
cars.head()

index  company          car_type  wheel-base  length engine-type  \
0      0    Honda       Convertible        88.6   168.8        dohc   
1      1    Honda       Convertible        88.6   168.8        dohc   
2      2    Honda  Four Wheel Drive        94.5   171.2        ohcv   
3      3  Hyundai         Salon car        99.8   176.6         ohc   
4      4  Hyundai         Salon car        99.4   176.6         ohc   

  num-of-cylinders  egine_capacity  average-km     price  Unnamed: 10  \
0             four             7.4    33.79614   87717.5          NaN   
1             four             7.4    33.79614  107250.0          NaN   
2              six            10.3    30.57746  107250.0          NaN   
3             four             6.8    38.62416   90675.0          NaN   
4             five             7.7    28.96812  113425.0          NaN   

   Unnamed: 11  Unnamed: 12  Unnamed: 13  Unnamed: 14  
0          NaN          NaN          NaN          NaN  
1          NaN          NaN          NaN          NaN  
2          NaN          NaN          NaN          NaN  
3          NaN          NaN          NaN          NaN  
4          NaN          NaN          NaN          NaN

In [28]:
# printing the last 5 rows
cars.tail()

index     company   car_type  wheel-base  length engine-type  \
56     81      Toyota  Salon car        97.3   171.7         ohc   
57     82      Toyota  Salon car        97.3   171.7         ohc   
58     86      Toyota  Salon car        97.3   171.7         ohc   
59     87  Mitsubishi  Salon car       104.3   188.8         ohc   
60     88  Mitsubishi      Wagon       104.3   188.8         ohc   

   num-of-cylinders  egine_capacity  average-km    price  Unnamed: 10  \
56             four             5.7    43.45218  51837.5          NaN   
57             four             3.5    59.54558  51967.5          NaN   
58             four             6.7    41.84284  64967.5          NaN   
59             four             7.6    37.01482  84110.0          NaN   
60             four             7.6    37.01482  87197.5          NaN   

    Unnamed: 11  Unnamed: 12  Unnamed: 13  Unnamed: 14  
56          NaN          NaN          NaN          NaN  
57          NaN          NaN          NaN          NaN  
58          NaN          NaN          NaN          NaN  
59          NaN          NaN          NaN          NaN  
60          NaN          NaN          NaN          NaN

### b. Clean the dataset and update the CSV file

In [29]:
# removing all columns with unnamed
cars3 = cars.drop(columns=['Unnamed: 14', 'Unnamed: 13', 'Unnamed: 12', 'Unnamed: 11', 'Unnamed: 10'])
cars3

index     company          car_type  wheel-base  length engine-type  \
0       0       Honda       Convertible        88.6   168.8        dohc   
1       1       Honda       Convertible        88.6   168.8        dohc   
2       2       Honda  Four Wheel Drive        94.5   171.2        ohcv   
3       3     Hyundai         Salon car        99.8   176.6         ohc   
4       4     Hyundai         Salon car        99.4   176.6         ohc   
..    ...         ...               ...         ...     ...         ...   
56     81      Toyota         Salon car        97.3   171.7         ohc   
57     82      Toyota         Salon car        97.3   171.7         ohc   
58     86      Toyota         Salon car        97.3   171.7         ohc   
59     87  Mitsubishi         Salon car       104.3   188.8         ohc   
60     88  Mitsubishi             Wagon       104.3   188.8         ohc   

   num-of-cylinders  egine_capacity  average-km     price  
0              four             7.4    33.79614   87717.5  
1              four             7.4    33.79614  107250.0  
2               six            10.3    30.57746  107250.0  
3              four             6.8    38.62416   90675.0  
4              five             7.7    28.96812  113425.0  
..              ...             ...         ...       ...  
56             four             5.7    43.45218   51837.5  
57             four             3.5    59.54558   51967.5  
58             four             6.7    41.84284   64967.5  
59             four             7.6    37.01482   84110.0  
60             four             7.6    37.01482   87197.5  

[61 rows x 10 columns]

In [30]:
# removing na values from the data set
cars3_clean = cars3.dropna()
cars3_clean

index     company          car_type  wheel-base  length engine-type  \
0       0       Honda       Convertible        88.6   168.8        dohc   
1       1       Honda       Convertible        88.6   168.8        dohc   
2       2       Honda  Four Wheel Drive        94.5   171.2        ohcv   
3       3     Hyundai         Salon car        99.8   176.6         ohc   
4       4     Hyundai         Salon car        99.4   176.6         ohc   
5       5     Hyundai         Salon car        99.8   177.3         ohc   
6       6     Hyundai             Wagon       105.8   192.7         ohc   
7       9         Bmw         Salon car       101.2   176.8         ohc   
8      10         Bmw         Salon car       101.2   176.8         ohc   
9      11         Bmw         Salon car       101.2   176.8         ohc   
10     13         Bmw         Salon car       103.5   189.0         ohc   
11     14         Bmw         Salon car       103.5   193.8         ohc   
12     15         Bmw         Salon car       110.0   197.0         ohc   
13     16     Kantaka  Four Wheel Drive        88.4   141.1           l   
14     17     Kantaka  Four Wheel Drive        94.5   155.9         ohc   
15     18     Kantaka         Salon car        94.5   158.8         ohc   
16     19     Kantaka  Four Wheel Drive        93.7   157.3         ohc   
17     20     Kantaka  Four Wheel Drive        93.7   157.3         ohc   
18     27     Kantaka             Wagon        96.5   157.1         ohc   
19     28     Kantaka         Salon car        96.5   175.4         ohc   
20     29     Kantaka         Salon car        96.5   169.1         ohc   
21     30     Kantaka         Salon car        94.3   170.7         ohc   
24     33     Kantaka         Salon car       113.0   199.6        dohc   
25     34     Kantaka         Salon car       113.0   199.6        dohc   
26     35     Kantaka         Salon car       102.0   191.7        ohcv   
27     36       Mazda  Four Wheel Drive        93.1   159.1         ohc   
28     37       Mazda  Four Wheel Drive        93.1   159.1         ohc   
29     38       Mazda  Four Wheel Drive        93.1   159.1         ohc   
30     39       Mazda  Four Wheel Drive        95.3   169.0       rotor   
31     43       Mazda         Salon car       104.9   175.0         ohc   
32     44      Toyota         Salon car       110.0   190.9         ohc   
33     45      Toyota             Wagon       110.0   190.9         ohc   
34     46      Toyota         Salon car       120.9   208.1        ohcv   
35     47      Toyota           hardtop       112.0   199.2        ohcv   
36     49  Mitsubishi  Four Wheel Drive        93.7   157.3         ohc   
37     50  Mitsubishi  Four Wheel Drive        93.7   157.3         ohc   
38     51  Mitsubishi         Salon car        96.3   172.4         ohc   
39     52  Mitsubishi         Salon car        96.3   172.4         ohc   
40     53      Nissan         Salon car        94.5   165.3         ohc   
41     54      Nissan         Salon car        94.5   165.3         ohc   
42     55      Nissan         Salon car        94.5   165.3         ohc   
43     56      Nissan             Wagon        94.5   170.2         ohc   
44     57      Nissan         Salon car       100.4   184.6        ohcv   
45     61  Mitsubishi       Convertible        89.5   168.9        ohcf   
46     62  Mitsubishi       Convertible        89.5   168.9        ohcf   
48     66       Honda  Four Wheel Drive        95.7   158.7         ohc   
49     67       Honda  Four Wheel Drive        95.7   158.7         ohc   
50     68       Honda  Four Wheel Drive        95.7   158.7         ohc   
51     69       Honda             Wagon        95.7   169.7         ohc   
52     70       Honda             Wagon        95.7   169.7         ohc   
53     71       Honda             Wagon        95.7   169.7         ohc   
54     79       Honda             Wagon       104.5   187.8        dohc   
55     80      Toyota        

### c. Find the most expensive car company name

In [31]:
# printing the details of the most expensive car company
most_exp_com = cars3_clean.sort_values('price', ascending=False).head(1)
most_exp_com

index company car_type  wheel-base  length engine-type num-of-cylinders  \
35     47  Toyota  hardtop       112.0   199.2        ohcv            eight   

    egine_capacity  average-km     price  
35            12.3    22.53076  295100.0

In [32]:
# printing the most expensive car company using iat method
print(most_exp_com.iat[0,1])

Toyota


### d. print all Kantaka cars details

In [33]:
# printing all Kantaka cars details using the loc method
cars3_clean.loc[cars3_clean['company']=='Kantaka']

index  company          car_type  wheel-base  length engine-type  \
13     16  Kantaka  Four Wheel Drive        88.4   141.1           l   
14     17  Kantaka  Four Wheel Drive        94.5   155.9         ohc   
15     18  Kantaka         Salon car        94.5   158.8         ohc   
16     19  Kantaka  Four Wheel Drive        93.7   157.3         ohc   
17     20  Kantaka  Four Wheel Drive        93.7   157.3         ohc   
18     27  Kantaka             Wagon        96.5   157.1         ohc   
19     28  Kantaka         Salon car        96.5   175.4         ohc   
20     29  Kantaka         Salon car        96.5   169.1         ohc   
21     30  Kantaka         Salon car        94.3   170.7         ohc   
24     33  Kantaka         Salon car       113.0   199.6        dohc   
25     34  Kantaka         Salon car       113.0   199.6        dohc   
26     35  Kantaka         Salon car       102.0   191.7        ohcv   

   num-of-cylinders  egine_capacity  average-km     price  
13            three             3.2    75.63898   33481.5  
14             four             4.7    61.15492   40917.5  
15             four             4.7    61.15492   42737.5  
16             four             4.5    49.88954   41450.5  
17             four             4.5    49.88954   40488.5  
18             four             5.1    48.28020   47417.5  
19             four             6.7    38.62416   84142.5  
20             four             6.7    40.23350   67242.5  
21             four             5.2    38.62416   44102.5  
24              six            11.7    24.14010  209625.0  
25              six            11.7    24.14010  231075.0  
26           twelve            17.5    20.92142  234000.0

### e. counting the totalcars per company

In [34]:
# counting the totalcars per company using values_count method
cars3_clean.company.value_counts()

Kantaka       12
Honda         10
Toyota         8
Mitsubishi     8
Bmw            6
Mazda          5
Nissan         5
Hyundai        4
Name: company, dtype: int64

### f. Finding each company’s Highest price car

In [35]:
#grouping companies by name
company_3 = cars3_clean.groupby('company')

#getting each company's highest priced car using max method
company_3[['car_type', 'price']].max()

car_type     price
company                        
Bmw         Salon car  268547.5
Honda           Wagon  107250.0
Hyundai         Wagon  122980.0
Kantaka         Wagon  234000.0
Mazda       Salon car  119236.0
Mitsubishi      Wagon  240682.0
Nissan          Wagon   87743.5
Toyota        hardtop  295100.0

### g. Find the average mileage of each car making company

In [36]:
# Finding the average mileage of each car making company using the mean method
company_3[['car_type', 'average-km']].mean()

average-km
company               
Bmw          30.577460
Honda        42.164708
Hyundai      32.186800
Kantaka      44.390962
Mazda        45.061520
Mitsubishi   39.831165
Nissan       50.533276
Toyota       40.032333

### h. Sort all cars by Price column

In [37]:
# Sorting all cars by Price column in descending order
cars3_clean.sort_values(by=['price'], ascending=False)

index     company          car_type  wheel-base  length engine-type  \
35     47      Toyota           hardtop       112.0   199.2        ohcv   
11     14         Bmw         Salon car       103.5   193.8         ohc   
34     46      Toyota         Salon car       120.9   208.1        ohcv   
46     62  Mitsubishi       Convertible        89.5   168.9        ohcf   
12     15         Bmw         Salon car       110.0   197.0         ohc   
26     35     Kantaka         Salon car       102.0   191.7        ohcv   
25     34     Kantaka         Salon car       113.0   199.6        dohc   
45     61  Mitsubishi       Convertible        89.5   168.9        ohcf   
24     33     Kantaka         Salon car       113.0   199.6        dohc   
10     13         Bmw         Salon car       103.5   189.0         ohc   
33     45      Toyota             Wagon       110.0   190.9         ohc   
32     44      Toyota         Salon car       110.0   190.9         ohc   
9      11         Bmw         Salon car       101.2   176.8         ohc   
6       6     Hyundai             Wagon       105.8   192.7         ohc   
31     43       Mazda         Salon car       104.9   175.0         ohc   
4       4     Hyundai         Salon car        99.4   176.6         ohc   
8      10         Bmw         Salon car       101.2   176.8         ohc   
2       2       Honda  Four Wheel Drive        94.5   171.2        ohcv   
1       1       Honda       Convertible        88.6   168.8        dohc   
7       9         Bmw         Salon car       101.2   176.8         ohc   
54     79       Honda             Wagon       104.5   187.8        dohc   
5       5     Hyundai         Salon car        99.8   177.3         ohc   
3       3     Hyundai         Salon car        99.8   176.6         ohc   
44     57      Nissan         Salon car       100.4   184.6        ohcv   
0       0       Honda       Convertible        88.6   168.8        dohc   
60     88  Mitsubishi             Wagon       104.3   188.8         ohc   
19     28     Kantaka         Salon car        96.5   175.4         ohc   
59     87  Mitsubishi         Salon car       104.3   188.8         ohc   
30     39       Mazda  Four Wheel Drive        95.3   169.0       rotor   
20     29     Kantaka         Salon car        96.5   169.1         ohc   
58     86      Toyota         Salon car        97.3   171.7         ohc   
53     71       Honda             Wagon        95.7   169.7         ohc   
39     52  Mitsubishi         Salon car        96.3   172.4         ohc   
57     82      Toyota         Salon car        97.3   171.7         ohc   
56     81      Toyota         Salon car        97.3   171.7         ohc   
52     70       Honda             Wagon        95.7   169.7         ohc   
55     80      Toyota         Salon car        97.3   171.7         ohc   
43     56      Nissan             Wagon        94.5   170.2         ohc   
18     27     Kantaka             Wagon        96.5   157.1         ohc   
40     53      Nissan         Salon car        94.5   165.3         ohc   
38     51  Mitsubishi         Salon car        96.3   172.4         ohc   
51     69       Honda             Wagon        95.7   169.7         ohc   
42     55      Nissan         Salon car        94.5   165.3         ohc   
29     38       Mazda  Four Wheel Drive        93.1   159.1         ohc   
21     30     Kantaka         Salon car        94.3   170.7         ohc   
41     54      Nissan         Salon car        94.5   165.3         ohc   
15     18     Kantaka         Salon car        94.5   158.8         ohc   
50     68       Honda  Four Wheel Drive        95.7   158.7         ohc   
16     19     Kantaka  Four Wheel Drive        93.7   157.3         ohc   
49     67       Honda  Four Wheel Drive        95.7   158.7         ohc   
14     17     Kantaka  Four Wheel Drive        94.5   155.9         ohc   
17     20     Kantaka  Four Wheel Drive        93.7   157.3         ohc   
37     50  Mitsubishi  Four W

### i. Concatenate two data frames using the following two dictionaries

In [38]:
#Ghana cars dictionary
GhanaCars = {'Company': ['KANTAKA', 'VW', 'BMV', 'NEOPLAN'], 'Price': [23845, 171995, 135925 , 71400]}
#Japanese cars dictionary
JapaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}


In [39]:
# generating data frames from the dictionaries
gh_cars = pd.DataFrame(GhanaCars)
jp_cars = pd.DataFrame(JapaneseCars)

In [40]:
#concattenating the two data frames using the concat method
cars_conc = pd.concat([gh_cars, jp_cars], keys=["Ghana Cars", 'Japan Cars'])
cars_conc

Company   Price
Ghana Cars 0      KANTAKA   23845
           1           VW  171995
           2          BMV  135925
           3      NEOPLAN   71400
Japan Cars 0       Toyota   29995
           1        Honda   23600
           2       Nissan   61500
           3  Mitsubishi    58900